spring:
  datasource:
    url: jdbc:mysql://mysql:3306/board
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
